### ISSUE TITLE
Minor : Link to the documentation of PAH is for AAP2.1

### ISSUE THREAD

**Issue by idhaoui** [ansible-learnfest/ansible-learnfest-guide#14]
Make sure to update the link to the latest version.

https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/managing_red_hat_ansible_content_collections_and_ansible_galaxy_collections_in_automation_hub/assembly-creating-tokens-in-automation-hub

**Comment by cbolz** [comment]
closed with https://github.com/ansible-learnfest/ansible-learnfest-guide/pull/16
