### ISSUE TITLE
Ansible-lint on RHPDS setup complains from yamllint

### ISSUE THREAD

**Issue by idhaoui** [ansible-learnfest/ansible-learnfest-guide#15]
ansible-lint complains of missing yamllint module while it's already installed

Command failed: ansible-lint  --offline --nocolor -f codeclimate "/home/student/playbook-example.yml"
WARNING  /usr/lib/python3.9/site-packages/ansible/_vendor/init.py:42: UserWarning: One or more Python packages bundled by this ansible-core distribution were already loaded (packaging). This may result in undefined behavior.
  warnings.warn('One or more Python packages bundled by this ansible-core distribution were already '

Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
	sys.exit(_run_cli_entrypoint())
  File "/usr/lib/python3.9/site-packages/ansiblelint/main.py", line 253, in _run_cli_entrypoint
	sys.exit(main(sys.argv))
  File "/usr/lib/python3.9/site-packages/ansiblelint/main.py", line 168, in main
	from ansiblelint.rules import RulesCollection
  File "/usr/lib/python3.9/site-packages/ansiblelint/rules/init.py", line 30, in <module>
	import ansiblelint.yaml_utils
  File "/usr/lib/python3.9/site-packages/ansiblelint/yaml_utils.py", line 35, in <module>
	from yamllint.config import YamlLintConfig
ModuleNotFoundError: No module named 'yamllint'

**Comment by idhaoui** [comment]
Sounds like a known bug : https://github.com/ansible/ansible-lint/issues/1507

**Comment by idhaoui** [comment]
[student@ansible-1 ~]$ ansible-lint --version
ansible-lint 5.0.8 using ansible 2.13.3
No module named 'ansible'
FATAL: ansible-lint requires a version of Ansible package >= 2.9, but none was found. Please install a compatible version using the same python interpreter. See https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-with-pip

**Comment by cbolz** [comment]
you seem to do this on ansible-1, not the bastion host?
did you find the root cause since I was not able to reproduce?

**Comment by idhaoui** [comment]
The environment seems to have mismatch in the ansible-core vs ansible-lint version.

as a workaround :

`$ sudo dnf remove ansible-core`
`$ sudo dnf install ansible-navigator ansible-lint ansible-core-2.12.1 podman`

**Comment by idhaoui** [comment]
Below is the problem that could be faced...

![image](https://user-images.githubusercontent.com/8156748/207604996-bfc05b2b-39ad-4ddb-991f-27335d0bd680.png)

**Comment by idhaoui** [comment]
Christian suggested workaround

- install all packages needed as per the lab guide then downgrade ansible-core.

` sudo dnf install ansible-core-2.12.1` or `sudo dnf downgrade ansible-core`

I will update the documentation accordingly

**Comment by cbolz** [comment]
can this closed after merging #22 ?

**Comment by idhaoui** [comment]
#22 is merged, why didn't you close it :)
